name: Run callable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/callable_workflow.yml
    with:
      input1: Ipsum
  read-vars:
    name: Read vars
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Read vars
        run: |
          echo "read vars - output1=${{ needs.call-workflow.outputs.output1 }}, output2=${{ needs.call-workflow.outputs.output2 }}"
