name: Step output

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Who?
        required: true
        options:
          - Jane
          - John

jobs:
  build:
    name: Step output
    runs-on: ubuntu-latest
    steps:
    - name: Create vars
      id: vars
      run: echo "var1=${{ github.event.inputs.platform }}\nvar2=var2" >> $GITHUB_OUTPUT
    - name: Read vars
      run: echo "read vars - var1=${{ steps.vars.outputs.var1 }}, var2=${{ steps.vars.outputs.var2 }}"
