name: Step output

on:
  workflow_dispatch:
    inputs:
      who:
        type: choice
        description: Who?
        required: true
        options:
          - Jane
          - John

jobs:
  build:
    name: Step output
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@main
    - name: Create vars
      id: vars
      run: |
        printf "\n" >> $GITHUB_OUTPUT
        printf "var1=${{ github.event.inputs.who }}\n" | tee $GITHUB_OUTPUT
        printf "var2=var2\n" | tee $GITHUB_OUTPUT
    - name: Create vars with Node script
      id: nodescript
      run: node ./.github/workflows/step-output-node-script.js | tee $GITHUB_OUTPUT
    - name: Read vars
      run: |
        echo "read vars - var1=${{ steps.vars.outputs.var1 }}, var2=${{ steps.vars.outputs.var2 }}"
        echo "read vars from Node script - var1=${{ steps.nodescript.outputs.nodevar1 }}, var2=${{ steps.nodescript.outputs.nodevar2 }}"
